services:

  postgres:
    image: postgres:16
    container_name: theproject_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0
      POSTGRES_DB: collaboration_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: collab_backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: collab_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
