spring.application.name=collaborationTool

spring.datasource.url=jdbc:postgresql://postgres:5432/collaboration_db
spring.datasource.username=postgres
spring.datasource.password=0


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
